### ISSUE TITLE
md-input-container does not respect theme

### ISSUE THREAD

**Issue by Stabzs** [marcosmoura/vue-material#104] opened 2016-11-21 07:02 UTC
Versions: v0.3.1, v0.3.3.

When a theme is applied to `md-input-container` or `md-input`, the theme is not applied.  This is currently present in the demo under https://marcosmoura.github.io/vue-material/#/components/input -> Themed.  In the demo, the two elements are supposed to be overridden to green and brown but they both retain the original color.

**Comment by marcosmoura** [comment] 2016-11-21 16:42
O noticed that. The problem is that the directive change the element class and the ```md-input-container``` is reactive, so soon as the directive change the class the container changes his class to another. I will change that ASAP. The workaround is to wrap the elements in a extra div to fix the problem.

**Comment by Stabzs** [comment] 2016-11-21 17:49
Thanks for the workaround.  Wrapping the `md-input-container` in a div and applying the theme to that div does indeed work!

**Comment by marcosmoura** [comment] 2016-12-05 02:58
This will be fixed when the new Theme Engine comes.

**Closed by marcosmoura** 2016-12-05 02:58 UTC
Labels: bug, improvement
