### ISSUE TITLE
md-input of type number allows letters

### ISSUE THREAD

**Issue by d3radicated** [marcosmoura/vue-material#494] opened 2017-02-13 06:30 UTC
### Steps to reproduce
1. Go to Components > Input in the docs.
2. Type a letter.
### Which browser?
Mozilla Firefox 51.0.1
### What is expected?
Input will not parse letters.
### What is actually happening?
Input allows letters. It also breaks label rendering when unfocused.

### Reproduction Link
[Imgur](http://i.imgur.com/VM0QuVg.gifv)

**Comment by marcosmoura** [comment] 2017-02-13 16:17
I couldn't reproduce this issue on Firefox. Even on Firefox Mobile this works fine

**Comment by d3radicated** [comment] 2017-02-13 16:31
What version is your Firefox? I have 51.0.1 (x32).

In Google Chrome 56.0.2924.87 (x64), it works flawlessly.

**Comment by marcosmoura** [comment] 2017-02-13 16:51
I've tested on 49.0.2 (64-bit) and 51.0.1 (64-bit). Both on MacOS Sierra machines. Worked just fine. :(

**Comment by derekschlesselman** [comment] 2017-02-13 21:48
I can confirm this issue exists in Firefox 51.0.1 (64-bit) on Windows 7. It appears Firefox handles number inputs differently as it allows for letters to be entered and then marks the field invalid.

**Comment by marcosmoura** [comment] 2017-02-13 21:55
There is some implementations that could prevent this behaviour. Since this a browser feature, I will close this issue.

**Closed by marcosmoura** 2017-02-13 21:55 UTC
Labels: needs repro
