### ISSUE TITLE
misplaced md-button icons when put inside md-table

### ISSUE THREAD

**Issue by amgadserry** [marcosmoura/vue-material#642] opened 2017-03-25 14:04 UTC
### Steps to reproduce
create an md-table and put md-button with an icon inside any of its cells
### Which browser?

Chrome: Version 56.0.2924.87 (64-bit)
### What is expected?
centered icons inside button
<a href="https://postimg.org" target="_blank"><img src="https://s9.postimg.org/9xt6375un/FireShot_Capture_8___Components___Table___Vue_Ma.png" alt="FireShot Capture 8 - Components - Table - Vue Ma"/></a><br /><a target='_blank' href='https://postimage.org/'>image upload free</a><br /><br />
### What is actually happening?
<a href="https://postimg.org" target="_blank"><img src="https://s9.postimg.org/llimk05lr/FireShot_Capture_7___Components___Table___Vue_Ma.png" alt="FireShot Capture 7 - Components - Table - Vue Ma"/></a><br /><a target='_blank' href='https://postimage.org/'>image upload free</a><br /><br />
### Cause 
```
.md-button.md-fab .md-icon, .md-button.md-icon-button .md-icon {
    position: absolute;
    top: 1px;
    right: 0;
    bottom: 0;
    left: 0;
}
```
### Fix
```
.md-table .md-button.md-fab .md-icon, .md-table .md-button.md-icon-button .md-icon {
    position: static;
}

```

**Comment by d3radicated** [comment] 2017-03-25 16:47
Duplicate of #534. Fixed in `develop` branch via pull request #538.

**Closed** 2017-03-25 21:08 UTC
