### ISSUE TITLE
v-model on input field --- moves cursor to end of input field

### ISSUE THREAD

**Issue by web-surfer** [marcosmoura/vue-material#412] opened 2017-01-26 21:57 UTC
### Steps to reproduce
Attach v-model to an input field like this:

    <md-input-container>
        <label>Username</label>
        <md-input v-model="username"></md-input>
    </md-input-container>

    data() {
        username: ''
    }
### Which browser?
- Latest version of Chrome
- IE 11
- NOT A PROBLEM IN: Latest Firefox

### What is actually happening?
When you click anywhere inside of a string inside an input field, after you input one character, the blinking cursor goes to the end of the string. 

This happens if the input field is attached with v-model, and only in Chrome and at least IE 11. This does not happen in the latest Firefox.

### Reproduction Link
Try for yourself in Chrome or IE 11:
http://codepen.io/anon/pen/NdaOKE

Enter some text in the `username` field (i.e. "testing"). Then click anywhere inside the text, and try typing. After inputting one character, the blinking cursor will go to the end of the string.

**Comment by Morgul** [comment] 2017-01-26 23:19
This looks like a duplicate of #367.

**Closed** 2017-01-30 20:14 UTC
Labels: duplicated
