### ISSUE TITLE
md-table in combination with vuex causes crash

### ISSUE THREAD

**Issue by linde12** [marcosmoura/vue-material#91] opened 2016-11-17 12:37 UTC
I'm experiencing some issues with `<md-table>` when i create my Vuex store. Other elemes such as `<md-button>` and `<md-card>` work fine but the table gives me the following error:
```
Uncaught TypeError: Cannot read property '$el' of undefined(…)
```

If i wrap the table in a `<md-card>` add the class `md-table-card` to that card then it works fine. This makes me suspect that `getClosestVueParent` in `<md-table>` has something to do with it.

All i have to do to reproduce this is:

1. Initialize VueMaterial with Vue.use() and register a theme
2. Initialize Vuex with Vue.use() and create a new store `new Vuex.Store({})`
3. Boot up app(don't even have to pass the store) with `new Vue({...})` which renders a `<md-table>`

I'm using the vue-cli's webpack template and my versions are:
- vue@2.0.6
- vuex@2.0.0
- vue-material@0.3.1

**Comment by Morgul** [comment] 2016-11-17 21:49
This looks like it's related to #88. Both issues are probably fixed by #90.

**Comment by linde12** [comment] 2016-11-17 21:51
Ah, yes i looked at that issue and thought it was similar but i was unsure. I will try to apply the fix and come back with results

**Comment by linde12** [comment] 2016-11-18 08:30
Hmm, i still seem to be getting it even after applying the fix to `getClosestParent`

I will verify again once #90 is in a build and if it still doesn't work i will be back with feedback

**Comment by pauloramires** [comment] 2016-11-18 11:59
Hi, I reproduced your case and tested it with #90,  got no errors. Have you rebuild the module after applying the patch?
However I will also be waiting to hear from Marcos to see if it is a proper fix.

**Comment by linde12** [comment] 2016-11-18 12:10
@pauloramires Hey! I'm pretty sure that i did but something might have gone wrong. I have a repo called vue-test where this happens. But, yeah, i'll wait for the fix and we'll see if it works. For me this is no problem as i'm just testing vue with vue-material. I just thought i'd report it.

**Comment by marcosmoura** [comment] 2016-11-18 23:43
Well. This is kinda duplicated. There is another problem beyond this. I think that the ```md-table``` is not passing the correct *instance* to the ```md-table-card```. I will fix that ASAP.

**Closed** 2016-11-21 02:22 UTC
Labels: bug
